name = "MatrixMerge"
uuid = "3265bcac-820f-4b8a-8cd5-05a71ff46e33"
authors = ["Shane Kuei Hsien Chu (skchu@wustl.edu)"]
version = "0.1.1"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
FastaLoader = "139838d8-4077-4d8a-94e1-e6dd554a184c"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Mustache = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
SimDNA = "f325a362-c78e-481f-886d-076c680a7e4a"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CUDA = "3.10.1"
DataFrames = "1.3.4"
DataStructures = "0.18.13"
Documenter = "0.27.19"
DocumenterTools = "0.1.14"
DoubleFloats = "1.2.2"
FastaLoader = "0.1.2"
HypothesisTests = "0.10.10"
Mustache = "1.0.13"
SimDNA = "0.1.3"
StatsBase = "0.33.16"
CSV = "0.10.4"
julia = "1.7.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
